import 'package:json_annotation/json_annotation.dart';

part 'round_stats.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class RoundStats {
  final int totalScore;
  final int scoreDifferenceFromPar;

  RoundStats({
    required this.totalScore,
    required this.scoreDifferenceFromPar,
  });

  factory RoundStats.fromJson(Map<String, dynamic> json) =>
      _$RoundStatsFromJson(json);
  Map<String, dynamic> toJson() => _$RoundStatsToJson(this);
}
